name: on tag

on:
  push:
    tags:
      - stg-*
      - prd-*

jobs:
  build:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: set tag env
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Echo env before dev
        run: echo $ENV

      - name: set dev env
        run: echo "ENV=dev" >> $GITHUB_ENV

      - name: Echo env after dev
        run: echo $ENV

      - name: set stg env
        if: startsWith(env.TAG_NAME, 'stg')
        run: |
          echo "ENV=stg" >> $GITHUB_ENV
          echo "BASE_ENV=develop" >> $GITHUB_ENV

      - name: set prd env
        if: startsWith(env.TAG_NAME, 'prd')
        run: |
          echo "ENV=prd" >> $GITHUB_ENV
          echo "BASE_ENV=stg" >> $GITHUB_ENV

      - name: Echo env1
        run: |
          echo $ENV
          echo $BASE_ENV

      - name: Echo env2
        run: |
          echo ${{ env.ENV }}
          echo ${{ env.BASE_ENV }}

      - name: Echo1
        run: echo $TAG_NAME

      - name: Echo2
        run: echo ${{ env.TAG_NAME }}

      - name: dispatch1
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ryosukee/actions-test2
          token: ${{ secrets.MACHINE_USER_TOKEN }}
          event-type: echo
          client-payload: '{ "new_tag": "$TAG_NAME", "type": "1" }'

      - name: dispatch2
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ryosukee/actions-test2
          token: ${{ secrets.MACHINE_USER_TOKEN }}
          event-type: echo
          client-payload: '{ "new_tag": "${TAG_NAME}", "type": "2" }'

      - name: dispatch3
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ryosukee/actions-test2
          token: ${{ secrets.MACHINE_USER_TOKEN }}
          event-type: echo
          client-payload: '{ "new_tag": "${{ env.TAG_NAME }}", "type": "3" }'
