name: on tag

on:
  push:
    tags:
      - stg-*

jobs:
  build:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: set tag env
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Echo1
        run: echo $TAG_NAME

      - name: Echo2
        run: echo ${{ env.TAG_NAME }}

      - name: dispatch1
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ryosukee/actions-test2
          token: ${{ secrets.MACHINE_USER_TOKEN }}
          event-type: echo
          client-payload: '{ "new_tag": "$TAG_NAME", "type": "1" }'

      - name: dispatch2
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ryosukee/actions-test2
          token: ${{ secrets.MACHINE_USER_TOKEN }}
          event-type: echo
          client-payload: '{ "new_tag": $TAG_NAME, "type": "2" }'

      - name: dispatch3
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ryosukee/actions-test2
          token: ${{ secrets.MACHINE_USER_TOKEN }}
          event-type: echo
          client-payload: '{ "new_tag": "${{ env.TAG_NAME }}", "type": "3" }'

      - name: dispatch4
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ryosukee/actions-test2
          token: ${{ secrets.MACHINE_USER_TOKEN }}
          event-type: echo
          client-payload: '{ "new_tag": ${{ env.TAG_NAME }}, "type": "4" }'