name: on tag

on:
  push:
    tags:
      - stg-*

jobs:
  build:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: set tag env
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Echo1
        run: echo $TAG_NAME

      - name: Echo2
        run: echo ${{ env.TAG_NAME }}