name: push test

on: pull_request

jobs:
  push-test:
    name: push-test-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: add a file 
        run: touch hoge.txt
      
      - name: commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add .
          git commit -m "hore(ci): make format in"
      
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.event.pull_request.head.ref }}
